### PR TITLE
Swift 4.2

### PR DESCRIPTION
**Pull request by erikpoort**
Fixes some swift 4.2 errors.
Also resolves some warnings.

### CODE REVIEW

**Comment by genkernel** [comment]
Hi, is it possible to trigger travis check again?
Travis probably did not support swift 4.2 at the moment of pull request.
They do have support now with Xcode 10, according to this: https://docs.travis-ci.com/user/languages/objective-c/ 
with osx_image: xcode10

**Comment by erikpoort** [comment]
@genkernel I wasn't aware of the setting, as I haven't worked with travis.
It does pass now! :)

**Comment by loudmouth** [comment]
It would be really great to have this one reviewed and merged (assuming it get's approved).

**Comment by jimvanzummeren** [comment]
Sorry it took so long, looks good! Merging it and now and making a new release!

**Comment by loudmouth** [comment]
thanks @jimvanzummeren !

**Pull request merged**
