### PR TITLE
Fix deprecations that appeared in Xcode 9.2

### PR DESCRIPTION
**Pull request by loudmouth**
Also, any chance a new version could be published? I'm currently pointed at the HEAD of master to pull in the changes from my last PR.

### CODE REVIEW

**Comment by jvanzummeren** [comment]
@loudmouth Which changes are you referring to? What version of MarkyMark are you using? Doesn't MarkyMark 4.0.2 include all your previous pull requests?

https://github.com/M2Mobi/Marky-Mark/tree/4.0.2

**Comment by loudmouth** [comment]
Ahh, the pull request i'm referring to that's not published yet is #39 which was merged November 23rd.

4.0.2 was published exactly two months before that. It's not crucial to have a new version published actually. Probably more important to just get these two PR's merged. Caught #43 a few hours ago when i saw a bunch of text disappearing in my app.

**Comment by jvanzummeren** [comment]
Good to hear, 4.0.2 indeed includes #39. I'll try to make #42 and #43 happen this week :)

**Comment by loudmouth** [comment]
Thanks @jimvanzummeren !

Thought I'd also let you know that I'll be including this as a dependency in an example app for [contentful.swift](https://github.com/contentful/contentful.swift) as this library serves better for my purposes than any others I've found.

Thanks to you and your team for putting this lib together!

**Comment by jvanzummeren** [comment]
Thanks! @loudmouth

**Pull request merged**
