### PR TITLE
Add SPM

### PR DESCRIPTION
**Pull request by SMillerDev**
Gonna build packages for SPM and make the iOS department pay for it.

Make PHP developers great again

### CODE REVIEW

**Comment by simdani** [comment]
https://github.com/M2Mobi/Marky-Mark/issues/98

**Comment by simdani** [comment]
@SMillerDev your build is failing because of UIKit imports, will you fix it? :)

**Comment by SMillerDev** [comment]
I might

**Comment by SMillerDev** [comment]
You clearly have a higher interest in it then beating your colleagues though. You might be better off making your own pull request. You could be the hero that fixes this for all users of Marky-Mark.

**Comment by lvnkmn** [comment]
Couldn't (really) wait for this to be merged, it turned out to work just fine for me. Nice one Sean!

**Comment by SMillerDev** [comment]
@lvnkmn are you saying this implementation is correct and my tests are just wrong?

**Comment by lvnkmn** [comment]
Not trying to offend your tests here. It works for what I need it to do, that's all.

**Comment by SMillerDev** [comment]
I'm not at all offended, just disappointed in my google skills 😄

**Comment by simdani** [comment]
It works well if you import UIKit in missing files :)

**Comment by SMillerDev** [comment]
Remaining failure seems to be an issue with iOS 13 more then SPM. @M2Mobi/ios any ideas?

**Comment by lvnkmn** [comment]
I have been pointing to @SMillerDev  's repo because of this for quite a bit now. Any news on when this can be merged (and if needed completed)?

**Comment by lvnkmn** [comment]
@Basca, @ThijsBouma This branch and PR works for me in  swift package manager, however there's a couple of code changes that I don't think are appropriate:
1. Changes in podspec should not be needed for this
2. Commented out code in `package.swift`

Aside from that, some build settings have been changed, but have not resulted in travis tests actually succeeding.

What I'll do:
* I'll create a new pull request, using the changes that make sense.
* I'll close this PR as soon as that one is up.

What I'd like to know from you:
To what extend are you relying on the travis checks passing. Is local build and passing tests good enough? if that's the case we might be able to release this soon.

**Comment by SMillerDev** [comment]
> Aside from that, some build settings have been changed, but have not resulted in travis tests actually succeeding.

Afaik this was an iOS 13/Xcode 11 issue. If you can make a pull request to fix travis with Xcode 11 I can clean up this review a bit.

**Comment by lvnkmn** [comment]
Closed in favor of https://github.com/M2Mobi/Marky-Mark/pull/101

**Pull request closed without merging**
